name: Hello world
on:
  #schedule:
   # - cron: '*/10 * * * *'
  # Allow manual trigger for testing
  workflow_dispatch:
jobs:
  hello-world-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository
      - uses: actions/checkout@v7
      # Runs a single command using the runner shell
      - name: Run a one-line script
        run: echo "Hello world!"

  A:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Job A running after hello-world-job"

  B:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Job B running after hello-world-job"
